#!/bin/csh

cd data

foreach file (*.header)

    setenv base `basename $file .header`
    echo $base
    pwd
    echo $base | `pwd`/../PostGITM.exe

    if (-e ${base}.bin && -e ${base}.sat)then
       # Remove satellite file and header
       rm -f ${base}.sat ${file}
    else if (-e ${base}.bin) then
       # Remove block files and header
       rm -f ${base}.b[0-9][0-9][0-9][0-9] ${file}
    endif

end

cd ..
